### ISSUE TITLE
the same:attribute validation rule not working

### ISSUE THREAD

**Issue by CharlieMarket** [zackify/validify#24]
It seems that "same:attribute" is not working. This is due to in validateOnBlurOrChange method of FormBase you call validate with one value:
  const { formErrors } = validate(
      { [name]: value },
      { [name]: rules[name] },
      errorMessages,
      attributeNames
    );
This not allow to use another fields values for validation. The validatorjs library expect all values for evaluate multiple field conditions. So if we change the code to send all values the library works:

  const { formErrors } = validate(
       this.props.values, //  this = FormBase instance - The idea is to send all values for correct evaluation
      { [name]: rules[name] },
      errorMessages,
      attributeNames
    );
I hope this helps.

**Comment by zackify** [comment]
I’ve actually thought about this one before, it’s not quite that easy because if you pass all the rules and values, they will have error messages before you even type in a field possibly, which would be a problem. May need a slightly bigger change. Do you see what I’m saying? Thanks for bringing this up

**Comment by CharlieMarket** [comment]
I agree is a mayor change. But to rules with multiple value validation works, the values are needed.  Pass all rules is not needed, just the rule of the field, as your code shows. 
This little change allow use other fields in a custom rule too. For example, if I have a field with a rule using the second password field value ( named 2ndPass) in it, I can use this code to get the value:

Validator.register('myRule', function(value, requirement, attribute) {

  // Here we get the value of another field
  const secondPasswordValue = this.validator._flattenObject(this.validator.input)['2ndPass'];

 // Rule evaluation here

  return true of false; // It depends of evaluation 
} , 'My Rule fail on field :attribute');

**Comment by diegoper94** [comment]
I am having serious troubles because of this rule not working :( I really need it for password confirmation.

**Comment by diegoper94** [comment]
I tried with the confirmed rule but it does not work.

**Comment by zackify** [comment]
@diegoper94 add "required|" to your password fields then you will not have an issue

**Comment by diegoper94** [comment]
Yes but i need the password and confirm password fields to match, for that i need same: rule or confirmed but both of then dont work.

**Comment by zackify** [comment]
@diegoper94 show your rules. If you simply put required in addition to those rules, it will work.

**Comment by diegoper94** [comment]
```import React, { Component } from 'react';
import { Form } from 'react-validify';
import Input from '../CreateRecipe/Input';

class SignUp extends Component {

  render() {
    return (
    <div className="container">
      <div className="row">
        <div className="offset-md-3 col-md-6">
        <h2 className="create-recipe__header">Sign Up</h2>
        <Form 
          rules={{
          userName:'required|min:3',
          password:'required|between:6,10',
          password_confirmation:'required|same:password',
          email:'required|email'
          }}
          errorMessages={{
            'required.userName': 'Please provide a user name',
            'min.userName': 'The user name must contain at least 3 characters',
            'required.password': 'Please set a password',
            'between.password': 'The password must contain from 6 to 10 characters',
            'required.email': 'Please provide a email',
            'email.email': 'Please provide a valid email'
          }}>
          <div className="form-group">
            <label htmlFor="userName">User Name</label>
            <Input className="form-control" name="userName" id="userName" placeholder="example123" />
            <label htmlFor="password">Password</label>
            <Input className="form-control" name="password" id="password" type="password" />
            <label htmlFor="password_confirmation">Confirm Password</label>
            <Input className="form-control" name="password_confirmation" id="password_confirmation" type="password" />
            <label htmlFor="email">Email Address</label>
            <Input className="form-control" name="email" id="email" placeholder="example@gmail.com" />
          </div>
          <div>
          <button submit className="btn btn-success">Submit <i className="fas fa-arrow-circle-right"></i></button>
          </div>
        </Form>
      </div>
      </div> 
    </div>

    )
  }
}

export default SignUp;

**Comment by zackify** [comment]
does this work? https://github.com/skaterdav85/validatorjs#confirmed

**Comment by diegoper94** [comment]
It does not work also :( I really enjoy this library because it is easy and simple to use please could you fix that?

**Comment by diegoper94** [comment]
I would fix it by myself and share the fix but i am a begginer just playing around with react.

**Comment by zackify** [comment]
@diegoper94 if you would like me to debug it, please make a single file that I can paste into create-react-app that has your issue. So make a new CRA, and make it not work inside the index.js and i will copy and try to see whats wrong :)
